# Automatically migrated from legacy .beetsconfig.

directory: ~/Music/mp3
library: ~/Music/BeetsLibrary.blb
#plugins: fetchart embedart web mbcollection ftInTitle lyrics
plugins: fetchart embedart web mbcollection lyrics

musicbrainz:
    user: threv
    pass: musicbrainz242

paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: Compilations/$album/$track $artist - $title
    albumtype:soundtrack: Soundtracks/$album/$track $artist - $title

lastgenre:
    fallback_str: ''

lyrics:
    auto: false
